#!/usr/bin/python

#Write a Python program to read through the lines of the file, break each line into a list of words.THE INPUT IS A FILE AND OUTPUT SHOULD BE A LIST WHOSE ELEMENTS WILL BE WORDS OF THE FILE

# Use file dict_file_reference
print ("FILE USED AS INPUT FOR THIS PROGRAM is:: dict_file_reference")
fhand=open('dict_file_reference', 'r')

list1,list2=[],[]
list2=[]
i=0
for line in fhand:
    print ("len(line) and line are ::",len(line), line)
    line=line.split()
    print ("after split len(line) and line is::", len(line),line) 
    for i in range(len(line)):
        x=line[i]
        print ("x and i ::", x,i)
        list1.append(x)
    

print ("THE LENGTH OF THE LIST AND ITS CONTENTS ARE ::", len(list1), list1)
