#!/usr/bin/python

# FIBONACCI SERIES:- It starts with 0 and 1. And you keep adding the last 2 no's to get the next one.
#0,1,1,2,3,5,8,13,21,34 and so on.



count=int(raw_input("PLEASE ENTER THE NO OF FIBONNACI NO'S YOU WANT TO SEE::"))
print ("THE FIBONACCI OPERATION NEEDS TO BE PERFORMED %d times" %count)

def fib(count):
    l1=[0,1]
    if count==1:
       l1=l1[0]
    elif count==2:
       l1=l1[:]
    else:
       while (count > 2):
             l2=l1[len(l1)-1]+l1[len(l1)-2]
             l1.append(l2)
             count=count-1
       return l1

output=fib(count)
print ("THE FIBONACCI SEQUENCE IS ",output) 
