#!/usr/bin/python
import sys

"""

PROGRAM TO TAKE INPUT AS LIST OF NUMBERS AND PRINT THE MAX AND MIN OF THE NUMBERS 

"""

prompt=0
lst=[]

while 'TRUE':

     prompt= "ENTER THE NUMBER \n"
     number=raw_input(prompt)
     if number != 'OVER':
        try:
           number=int(number)
           lst.append(number)
        except:
           e=sys.exc_info()[0]
           print ("INVALID INPUT", e) 
     else:
           break

if len(lst) == 0:
   print ('THE LIST IS EMPTY', lst)
else:
   print ('THE LIST IS', lst)
   print ('THE MAX NO IN THE LIST IS', max(lst))
   print ('THE MIN NO IN THE LIST IS', min(lst))
