#!/usr/bin/python
import re

'''

FROM FILE TESTFILE3, MATCH FOLLOWING LINE AND GET THE TIME OUT OF IT.
From stephen.marquard@uct.ac.za Sat Jan 5 09:14:16 2008
'''

fname='testfile3'

fhand=open(fname,'r')

for line in fhand:

    line=line.rstrip()
#    match=re.findall('^From \S*@\S* ([a-zA-Z]* [a-zA-Z]* [0-9]* [0-9][0-9]: )',line)
    match=re.findall('^From .* ([0-9:]*) .*',line)
    if len(match) > 0:

       print ("&&&&", match)



