#!/usr/bin/python
import re

'''

Define a simple "spelling correction" function correct() that takes a string and sees to it that 1) two or more occurrences of the space character is compressed into one, and 2) inserts an extra space after a period if the period is directly followed by a letter. E.g. correct("This   is  very funny  and    cool.Indeed!") should return "This is very funny and cool. Indeed!" Tip: Use regular expressions!

'''


def correct(string):
    print ('IN THE FUNCTION CODE RIGHT NOW AND STRING PASSED IS::',string) 

    match=re.findall('[\S\s]*',string)
    if len(match) > 0:

       print ("&&&", match)   
    




prompt="ENTER A STRING WITH SOME EXTRA SPACES IN IT \n"
input=raw_input(prompt)
print ('THE STRING ENTERED BY USER IS::', input)

correct(input)


