#!/usr/bin/python

import re

fname='testfile3'
'''
fhand=open(fname,'r')
cnt=0
lst=[]
for line in fhand:
    line=line.rstrip()
    match= re.findall('[a-zA-Z0-9]\S+@\S+[a-zA-Z]',line)
    if len(match) > 0:
       print ("====", match)
       lst.append(match)
       cnt=cnt+1

print ('cnt is and len of match is', cnt,len(lst))

fhand.close()
'''
'''
fhand=open(fname,'r')
for line in fhand:
    line=line.rstrip()    
    if re.search('^X\S*: [0-9.]+[0.9]+',line):
       print ('****', line)

'''
output=[]
fhand=open(fname,'r')
for line in fhand:

    line=line.rstrip()
    match=re.findall('^X\S*: ([0-9.]+[0-9]+)',line)     
    if len(match) > 0:
       #print ("&&&", match)
       output=float(match[0])
       print ('THE FINAL OUTPUT IS:::', output)
        

