#!/usr/bin/python
import re
'''
Valid IP ADDRESS CHECK
'''


prompt='Enter a Valid ip address::\n'
input=raw_input(prompt)

input=input.rstrip()
print ('THE IP ADDRESS ENTERED BY USER IS::',input)
if re.search('[\d]{1,3}\.[\d]{1,3}\.[\d]{1,3}\.[\d]{1,3}$',input):
   print ('PASS')
else:
   print ('FAIL')

