#!/usr/bin/python
import sys

'''
Define a function generate_n_chars() that takes an integer n and a character c and returns a string, n characters long, consisting only of c:s. For example, generate_n_chars(5,"x") should return the string "xxxxx". (Python is unusual in that you can actually write an expression 5 * "x" that will evaluate to "xxxxx". For the sake of the exercise you should ignore that the problem can be solved in this manner.)
'''

def generate_n_chars(integer,char):

    str2=""
    integer=int(integer)
    print ("1", integer , char)
    while integer > 0:

          str2=str2+char
          integer=integer - 1
          print (integer)
    return str2
  



prompt=" ENTER THE CHAR FIRST::\n"
char=raw_input(prompt)

prompt="ENTER NO OF TIMES YOU WANT TO REPEAT THE CHAR::\n"
integer=raw_input(prompt)

try:
   int(integer)
   str(char)
   print ('THE CHAR IS',char,'WHICH NEEDS TO BE REPLICATED',integer,'TIMES')
   output=generate_n_chars(integer,char)
   print (' THE NEW STRING IS::', output)
except:
   e=sys.exc_info()[0]
   print (e)
 


