#!/usr/bin/python
'''
In cryptography, a Caesar cipher is a very simple encryption techniques in which each letter in the plain text is replaced by a letter some fixed number of positions down the alphabet. For example, with a shift of 3, A would be replaced by D, B would become E, and so on. The method is named after Julius Caesar, who used it to communicate with his generals. ROT-13 ("rotate by 13 places") is a widely used example of a Caesar cipher where the shift is 13. In Python, the key for ROT-13 may be represented by means of the following dictionary:

key = {'a':'n', 'b':'o', 'c':'p', 'd':'q', 'e':'r', 'f':'s', 'g':'t', 'h':'u', 
       'i':'v', 'j':'w', 'k':'x', 'l':'y', 'm':'z', 'n':'a', 'o':'b', 'p':'c', 
       'q':'d', 'r':'e', 's':'f', 't':'g', 'u':'h', 'v':'i', 'w':'j', 'x':'k',
       'y':'l', 'z':'m', 'A':'N', 'B':'O', 'C':'P', 'D':'Q', 'E':'R', 'F':'S', 
       'G':'T', 'H':'U', 'I':'V', 'J':'W', 'K':'X', 'L':'Y', 'M':'Z', 'N':'A', 
       'O':'B', 'P':'C', 'Q':'D', 'R':'E', 'S':'F', 'T':'G', 'U':'H', 'V':'I', 
       'W':'J', 'X':'K', 'Y':'L', 'Z':'M'}
Your task in this exercise is to implement an encoder/decoder of ROT-13. Once you're done, you will be able to read the following secret message:

   Pnrfne pvcure? V zhpu cersre Pnrfne fnynq!
Note that since English has 26 characters, your ROT-13 program will be able to both encode and decode texts written in English.

'''
dict1={'a':'n', 'b':'o', 'c':'p', 'd':'q', 'e':'r', 'f':'s', 'g':'t', 'h':'u',
       'i':'v', 'j':'w', 'k':'x', 'l':'y', 'm':'z', 'n':'a', 'o':'b', 'p':'c',
       'q':'d', 'r':'e', 's':'f', 't':'g', 'u':'h', 'v':'i', 'w':'j', 'x':'k',
       'y':'l', 'z':'m', 'A':'N', 'B':'O', 'C':'P', 'D':'Q', 'E':'R', 'F':'S',
       'G':'T', 'H':'U', 'I':'V', 'J':'W', 'K':'X', 'L':'Y', 'M':'Z', 'N':'A',
       'O':'B', 'P':'C', 'Q':'D', 'R':'E', 'S':'F', 'T':'G', 'U':'H', 'V':'I',
       'W':'J', 'X':'K', 'Y':'L', 'Z':'M'}
print dict1

lst="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
alphabet_list=list(lst)
print ('alphabet_list is', len(alphabet_list), alphabet_list)
dict={}
index=0
j=13
k=0
for i in range(len(alphabet_list)):
    if i < 13:
       dict[alphabet_list[i]]=alphabet_list[i+13] 
    elif i >= 13 and i <= 25:
       dict[alphabet_list[i]]=alphabet_list[i-13]
    elif i >=26 and i <= 38:
       dict[alphabet_list[i]]=alphabet_list[i+13]
    elif i >= 39:
       dict[alphabet_list[i]]=alphabet_list[i-13]
    print (alphabet_list[i], dict[alphabet_list[i]])                


print ('THE ROT13 ENCODER/DECODER DICTIONARY IS::\n', dict)
print (" ")

prompt='ENTER A SENTENCE WHICH YOU WANT TO ENCODE/DECODE ::\n'

input=raw_input(prompt)
input=input.rstrip()
punc=[',','.','?','!','-']
output=""
for i in range(len(input)):


    if input[i] in dict:
       output=output+dict[input[i]]
    elif input[i] in punc:
       output=output+input[i]
       continue
    else:
       output=output+input[i]
       continue



print ('THE DECODED TEXT IS::',output)
       
