#!/usr/bin/python

import re

fhand=open('xyz','r')
fhand1=open('mno','w')


expr="([a-zA-Z]+)\s+.*"
for line in fhand:
    line=line.rstrip()
    if re.search(expr,line):
       line1=re.search(expr,line)
       line1=line1.group(1)
       fhand1.write(line1)
       fhand1.write('\n')

  
