#!/usr/bin/python
import random
import re

def basic_infra(word,clue,userinput):
    print ('CHECKPOINT 1',word,clue)
    index_lst=[]
    dict={}
    ind=[]


    for i in range(len(clue)):
        print ('clue[i] and dict',clue[i],dict)    
        if clue[i] != " ":
           cluecnt=clue.count(clue[i])
           if cluecnt==1:
             x=re.search((clue[i]),word)   
             dict[x.start()]=clue[i]
             index_lst.append(x.start())
           else:
             for x in re.finditer(clue[i],word):
                 dict[x.start()]=clue[i]


    printclue=""
    print index_lst 
    print dict
    for i in range(len(word)):

        if i not in dict:
           printclue=printclue+" "
        else:
           printclue=printclue+dict[i]
    print ('2',printclue)    

    if userinput == "":
       initial_clues='\t'+printclue
       dash='\t'+'-----'
       print (" ")
       print initial_clues
       print dash
       print ('3',printclue)    
    else:
       if userinput in word:
          print ('I AM HERE',printclue)
          for match in re.finditer(userinput,word):
              ind.append(match.start())
          print ('index for',userinput,'is',ind)
          nuclue=""
          leng_index=len(ind)
          for i in range(len(printclue)):
              if i in ind:
                 if printclue[i]==" ":
                    print ('i and printclue',i,printclue,printclue[i],userinput)
                    nuclue=printclue.replace(printclue[i],userinput,1) 
                    print ('NEW NOCLUE',nuclue)
          printclue=nuclue
          print ('NEW printclue',printclue)
       else:
          print ('OOPS, TRY AGAIN') 

       initial_clues='\t'+printclue
       dash='\t'+'-----'
       print (" ")
       print initial_clues
       print dash
    return printclue





fhand=open('5letter_word_file','r')
lst=[]
for line in fhand:
    line=line.rstrip()
    lst.append(line)
actualword=random.choice(lst)
nuword=list(actualword)
leng=len(nuword)
no_of_clues=leng/2
clue=""
i=0
while (len(clue)<no_of_clues):
       rand=random.choice(nuword)
       if rand not in clue:
          clue=clue+rand
          nuword.remove(clue[i])
          i=i+1
       else:
          continue
input=""
print ('\n\n')
print ("*******************************************************")
print 'LETS PLAY HANGMAN.FOLLOWING IS THE PUZZLE AND ITS CLUES '
print ("*******************************************************")
print ('\n\n')
basic_infra(actualword,clue,input)
print ('\n\n')

while clue != actualword: 
      prompt='YOUR TURN TO ENTER A LETTER ::'
      input=raw_input(prompt)
      input=input.lower()
      input=input.rstrip()
      if input != 'exit':
          x=basic_infra(actualword,clue,input)
          print ('++++x is',x)
          clue=x
      else:
          break
else:
      print ('CONGRATULATIONS. YOU SOLVED THE HANGMAN.. READY FOR ANOTHER ONE ....')


