#!/usr/bin/python

from Tkinter import *
root=Tk()
logo=PhotoImage(file="/Users/AryanS/Downloads/3p_2.gif")
texts='I LOVE YOU SIM'
w1=Label(root, text=texts,image=logo,compound=TOP,padx=20,pady=20)
w1.pack(side='right')
root.mainloop()


