#!/usr/bin/python

'''
Question:
Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5,
between 2000 and 3200 (both included).
The numbers obtained should be printed in a comma-separated sequence on a single line.
'''
fhand1=open('1_file','w')

x=""
for i in range(2000,3200):

    if i%7==0 and i%5 != 0:
       x=str(i)+','
       fhand1.write(x)
    else:
       continue


