#!/usr/bin/python
import math
'''
Question:
Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.
Example:
0100,0011,1010,1001
Then the output should be:
1010
Notes: Assume the data is input by console.
'''

input='1100,1111,1000,0101'

input=input.split(',')
print (input, len(input))

def bin_dec(bin):
    no_dig=0
    for i in range(len(bin)):
        out=0
        x=""
        for j in range(len(bin[i])):
            x=x+bin[i][len(bin[i])-1-j]

        for j in range(len(x)):
            if x[j]=='1':
               out=out+math.pow(2,j+1)
               out=int(out)
            else:
               continue

        print ('decimal conversion of', bin[i],'is',out)
        print ('\n')

        if out%5==0:
           print ( bin[i],'is divisible by',5)
        else:
           continue

bin_dec(input)
                




