#!/usr/bin/python
import re
'''
Write a program that accepts a sentence and calculate the number of letters and digits.
Suppose the following input is supplied to the program:
hello world! 123
Then, the output should be:
LETTERS 10
DIGITS 3
'''

input="hello world! wasssup. My house no is 6052 and bike no is 3740"
letters=0
digits=0
for i in range(len(input)):

    if re.search('[a-zA-Z]{1}',input[i]):
       letters=letters+1
    elif re.search('[0-9]{1}',input[i]):
       digits=digits+1


print ('LETTERS ARE',letters)
print ('DIGITS ARE',digits)
