#!/usr/bin/python
import re
'''
A website requires the users to input username and password to register. Write a program to check the validity of password input by users.
Following are the criteria for checking the password:
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.
Example
If the following passwords are given as input to the program:
ABd1234@1,a F1#,2w3E*,2We3345
Then, the output of the program should be:
ABd1234@1
'''


prompt='ENTER PASSWORDS FOLLOWED BY COMMA::\n'
input=raw_input(prompt)

input=input.split(',')
match=[]
expr='[A-Z]+[a-z]+[0-9]+[\$#@]+'
for i in range(len(input)):
    for j in range(len(input[i])):
        if len(input[i]) > 6 and len(input[i]) < 12:
           if re.search(expr,input[i]):
              if input[i] not in match:
                 match.append(input[i])
        else:
            print (input[i], 'NOT A VALID PASSWD')  
if len(match) > 0:
   print ('PASSWORD MATCH',match)
else:
   print ('NO PASSWORD MATCHED')
