#!/usr/bin/python

'''
Write a program which can compute the factorial of a given numbers.
The results should be printed in a comma-separated sequence on a single line.
Suppose the following input is supplied to the program:
8
Then, the output should be:
40320
'''

a=[2,4,6,7,10,14]
lst=[]
for i in a:
    fact=1
    for j in range(1,i+1):
        fact=fact*j
    lst.append(fact)

print lst
