#!/usr/bin/python
import numpy
'''
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.
Note: i=0,1.., X-1; j=0,1,...Y-1.
Example
Suppose the following inputs are given to the program:
3,5
Then, the output of the program should be:
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]] 
'''
print numpy.zeros((3,5))
x=5
y=6
a=0
array=[]
for i in range(0,x):
    row=[]
    for j in range(0,y):

        row.append(i*j)
    array.append(row)

print array
