#!/usr/bin/python
import random
import string

'''
Write a password generator in Python. Be creative with how you generate passwords - strong passwords have a mix of lowercase letters, uppercase letters, numbers, and symbols. The passwords should be random, generating a new password every time the user asks for a new password. Include your run-time code in a main method.

Extra:

Ask the user how strong they want their password to be. For weak passwords, pick a word or two from a list.
'''

alpha=string.letters
alpha=list(alpha)

no_list=string.digits
no_list=list(no_list)

special_char='@#$%^&*!~.?'
special_char=list(special_char)

prompt='ENTER HOW STRONG YOU WANT THE PASSWORD. WEAK OR STRONG OR VERY STRONG::\n'
input=raw_input(prompt)
passwd=[]
randSp,randa,randC,randno="",'','',''
if input=='WEAK' or input=='weak':
   while len(passwd) < 6:
         randC=random.choice(alpha)
         if randC not in passwd:
            randC=randC.upper()
            passwd.append(randC)
            randC=""
         else:
            continue

         randa=random.choice(alpha)
         if randa not in passwd:
            randa=randa.lower()
            passwd.append(randa)
            randa=""
         else:
            continue

         randno=random.choice(no_list)
         if randno not in passwd:
            passwd.append(randno)
            randno=""
         else:
            continue

elif input=='STRONG' or input=='strong':
   while len(passwd) < 8:
         randC=random.choice(alpha)
         if randC not in passwd:
            randC=randC.upper()
            passwd.append(randC)
            randC=""
         else:
            continue

         randa=random.choice(alpha)
         if randa not in passwd:
            randa=randa.lower()
            passwd.append(randa)
            randa=""
         else:
            continue

         randno=random.choice(no_list)
         if randno not in passwd:
            passwd.append(randno)
            randno=""
         else:
            continue
  
      
         randSp=random.choice(special_char)
         if randSp not in passwd:
            passwd.append(randSp)
            randSp=""
         else:
            continue
else:
   print ('PLEASE ENTER A VALID CHOICE OF PROGRAM. EXITING NOW')
password=""
for i in range(len(passwd)):
    password=password+passwd[i]
print ('THE PASSWORD IS',password)
