#!/usr/bin/python
'''
Write a version of a palindrome recognizer that also accepts phrase palindromes such as "Go hang a salami I'm a lasagna hog.", "Was it a rat I saw?", "Step on no pets", "Sit on a potato pan, Otis", "Lisa Bonet ate no basil", "Satan, oscillate my metallic sonatas", "I roamed under it as a tired nude Maori", "Rise to vote sir", or the exclamation "Dammit, I'm mad!". Note that punctuation, capitalization, and spacing are usually ignored.
'''

def palindrome(str):

    print('THE PALINDROME STRING ENTERED IS :\n',str)
    output=""
    str1=""
    punctuation="'?!@#\,."
    for i in str:
        if (i !=" ") and (i not in punctuation):
           str1=str1+i
    str1=str1.lower()
           
    print('NEW PALINDROME STRING WITHOUT SPACES AND PUNCTUATION IS:',str1)        
    for i in range(0,len(str1)):
        if (str1[i] !=" ") and (str1[i] not in punctuation): 
           output=output+str1[len(str1)-1-i]

    output=output.lower()
    print('THE REVERSE OF THE STRING IS:',output)
    if (str1==output):
       print ("SUCCESSFUL")
    else:
       print ("FAILED")
         	  

prompt='ENTER A PALINDROME STRING:\n'
x=raw_input(prompt)
output=palindrome(x)


