#!/usr/bin/python
'''
Define a function max() that takes two numbers as arguments and returns the largest of them. Use the if-then-else construct available in Python. (It is true that Python has the max() function built in, but writing it yourself is nevertheless a good exercise.)
'''

def max_no(num1,num2):

    print('NUMBERS PASSED TO FUNCTIONS ARE %d %d' %(num1,num2))

   if (num1 > num2):
      return num1
   else:
      return num2






num=list[]
for x in range(0:2):
      prompt='ENTER THE NO:\n'
      num.append=raw_input(prompt)


print ('the numbers entered are',num)
output=max_no([num[0],num[1])
