#!/usr/bin/python
import re

'''

Define a simple "spelling correction" function correct() that takes a string and sees to it that 1) two or more occurrences of the space character is compressed into one, and 2) inserts an extra space after a period if the period is directly followed by a letter. E.g. correct("This   is  very funny  and    cool.Indeed!") should return "This is very funny and cool. Indeed!" Tip: Use regular expressions!

'''

def correct(input):
    str=""
    for i in range(0,len(input)):
        if (input[i] == " " and input[i+1] == " "):
           continue
        elif(input[i] == " "):
           str=str+input[i]
        else:
           str=str+input[i]
    print('THE FINAL OUTPUT IS:',str)    
    


prompt='ENTER A STRING WHICH HAS FEW SPACES IN IT:\n'
input=raw_input(prompt)

correct(input)





