#!/usr/bin/python

'''
The third person singular verb form in English is distinguished by the suffix -s, which is added to the stem of the infinitive form: run -> runs. A simple set of rules can be given as follows:

If the verb ends in y, remove it and add ies
If the verb ends in o, ch, s, sh, x or z, add es
By default just add s
Your task in this exercise is to define a function make_3sg_form() which given a verb in infinitive form returns its third person singular form. Test your function with words like try, brush, run and fix. Note however that the rules must be regarded as heuristic, in the sense that you must not expect them to work for all cases. Tip: Check out the string method endswith().

'''

def plural(str):

    print('THE STRING ENTERED IS:',str)
    if (str[len(str)-1] == 'y'):
       str=str[0:-1]+'ies' 

    elif (str[len(str)-1] == 'o' or (str[len(str)-1] == 'h' or str[len(str)-2] == 'c') or str[len(str)-1] == 's' or (str[len(str)-1] == 'h' or str[len(str)-2] == 's') or str[len(str)-1] == 'x' or str[len(str)-1] == 'z'): 
       str=str+'es'

    else:
       str=str+'s'

    return str

prompt='ENTER A WORD:\n'
input=raw_input(prompt)

output=plural(input)
print('THE OUTPUT IS:',output)

