#!/usr/bin/python
import sys
"""
Write a program to read through a mail log, build a histogram using
a dictionary to count how many messages have come from each email address,
and print the dictionary.

Enter file name: testfile3
{'gopal.ramasammycook@gmail.com': 1, 'louis@media.berkeley.edu': 3,
'cwen@iupui.edu': 5, 'antranig@caret.cam.ac.uk': 1,
'rjlowe@iupui.edu': 2, 'gsilver@umich.edu': 3,
'david.horwitz@uct.ac.za': 4, 'wagnermr@iupui.edu': 1,
'zqian@umich.edu': 4, 'stephen.marquard@uct.ac.za': 2,
'ray@media.berkeley.edu': 1}
"""
fhand= open('testfile3','r')
dict={}
lst=[]
count=0
for line in fhand:
    line=line.rstrip()
    if line.startswith('From:'):
        line=line.split()
        for i in line:
            if '@' in i:
                lst.append(i)


#print (lst)
for i in lst:
    count = lst.count(i)
    if i not in dict.values():
       key=i
       dict[key]=count
       print(dict[key],  'appears', key, 'times')


print('\n'*3)    
print dict
