#!/usr/bin/python

import string

a=string.letters
a=a.lower()
a=list(a)
a=sorted(set(a))
a=list(a)
b={}
cnt=0
while cnt != len(a):
      for i in range(len(a)):
          k=i+2 
          if a[i]=='y':
             k=0
             b[a[i]]=a[k] 
          elif a[i]=='z':
             k=1
             b[a[i]]=a[k] 
          else:
            # print (i,k,a[i],'becomes',a[k],cnt)
            b[a[i]]=a[k] 
          cnt=cnt+1

print b
strin="g fmnc wms bgblr rpylqjyrc gr zw fylb. rfyrq ufyr amknsrcpq ypc dmp. bmgle gr gl zw fylb gq glcddgagclr ylb rfyr'q ufw rfgq rcvr gq qm jmle. sqgle qrpgle.kyicrpylq() gq pcamkkclbcb. lmu ynnjw ml rfc spj."
print strin
strin=list(strin)
punc="'.()"
punc=list(punc)
newstr=""
for i in range(len(strin)):
    if strin[i] in b:
       newstr=newstr+b[strin[i]]
    else:
       newstr=newstr+strin[i]
print newstr
           
 



