#!/usr/bin/python
import re
fhand=open('2.file','r')
expr="[a-zA-Z0-9]+"
for line in fhand:
    line=line.rstrip()
    if re.search('([a-zA-Z0-9]+)',line): 
       res=re.search('([a-zA-Z0-9]+)',line)
       print ('match found in ',res.group(1))
       
