#!/usr/bin/python
import sys
import os
import random

list_bike = ['zx14r','aquila']

print ('MY BIKES ARE AS FOLLOWS',list_bike)

list_car = ['xuv500','honda city', 'esteem']
print ('CAR\'S I HAVE ARE AS FOLLOWS',list_car)

list_car.append('astar')
print ('UPDATED CAR LIST IS',list_car)
print('\n'*5)
automobiles = [list_bike,list_car]

print('LIST OF MY AUTOMOBILES ARE :',automobiles)

print("THE SECOND CAR I HAD WAS ", automobiles[1][1])

list_bike.insert(len(list_bike)+1,'r15')


print ('UPDATED BIKE LIST IS',list_bike)
print('\n'*3)
print('LIST OF MY AUTOMOBILES ARE :',automobiles)


list_bike.remove('aquila')
print ('UPDATED BIKE LIST IS',list_bike)

list_car.sort()
print ('UPDATED CAR LIST IS',list_car)

print('LIST OF MY AUTOMOBILES BEFORE ARE :',automobiles)
del automobiles[1][1]
print('LIST OF MY AUTOMOBILES ARE :',automobiles)
list_car.insert(1,'zica')
print ('UPDATED CAR LIST IS',min(list_car))


for x in list_car:
    print('PRINTING THE LIST IN THE LOOP:',x)

list_bike.append('aquila')
print ('UPDATED BIKE LIST IS',list_bike)
if 'aquila' in list_bike:
    print ('I HAD AQUILA BIKE ONCE')
else:
    print ('I NEVER HAD AQUILA BIKE')
