#!/usr/bin/python


str="I HAVE THE FASTEST BIKE IN THE WORLD: ZX14R"

print(str[0:len(str)-1])

print('PRINT LAST 10 CHAR:',str[-10:])
print('PRINT TILL LAST 10TH CHAR APPEARS:',str[:-10])



print('%c is the %dst char of my name which is %s' %('a',1,'aryan'))
